### PR TITLE
Add ForceWindowedFullscreen module and NativeDPadFix memory patch

### PR DESCRIPTION
**Pull request by RhythmLunatic**
I wrote a module to force the game to run in windowed fullscreen.
I also added build instructions for Visual Studio 2015 since I used that to make/build it.

### CODE REVIEW

**Comment by RhythmLunatic** [comment]
Now that I think about it OnGetWindowInfo could be changed so it draws in the middle, maybe it could be used to get actual 16:9 windowed fullscreen.

**Comment by RhythmLunatic** [comment]
I added a NativeDPadFix memory patch. It's like DPadFix but without dinput8 hooking.

I wrote it because I didn't want to have to remap my controllers in the steam shortcut and steam overwrites dinput8 hooking with its own so the DPadFix module won't work.

**Comment by delthas** [comment]
Nice work! I'll review it soon.

What about making the XInput stuff a regular mod rather than a memory patch? While it could sound overkill, and is definitely less fun than the very nice ASM you made 👍, maybe it'd be more intuitive for users to have a separate mod and enable and disable it in the main ini file rather than the memory patch one, considering it's not a trivial change like the other memory patches. (To be honest I'm not a huge fan of the memory patch stuff to start with, from a user point of view, as well as a developer point a view: it'll be easier to iterate on the mod if it's plain C rather than the ASM patch.)

Regarding licensing, I see you've added a copyright trailer to the mod file. Since it's the same license as the `LICENSE` in the repository, I suggest removing the copyright stuff from the file.

**Comment by RhythmLunatic** [comment]
There is no need for an XInput fix as a regular module since DPadFix already does it.
I also don't know how, I wrote it by hand instead of using a linker.

**Comment by delthas** [comment]
Finished reviewing the WindowedFullscreen mod. See https://github.com/delthas/SWRSToys/commit/442cfcf99fce461abeccccd85ccc09dbf9866a70 for changes I made:
- always use the full screen space rather than a 4:3 window (on my system, if the window does not use the full screen, the taskbar is not hidden and shows on top of the game window)
- hook the IDirectDevice3D9 creation code to set a viewport to cut off rendering artifacts to the right of the window (see the function at 0x414ED0 for the Direct3D setup code)
- the game window is on the left of the screen, and there's a black border on the right, it's not centered but it's still better than 4:3 imo because it looks better-ish and the taskbar is really hidden now
- use detour for hooking functions rather than the terrible hook code from windowresizer (which should really be rewritten but that's for another PR)
- removed the copyright notice according to our discussion
- some minor reformatting nitpicks

I'll review the memory patch part later.

**Comment by delthas** [comment]
> To write it in C I'd have to have some way of jumping to my function and back at that exact spot in memory.

Right. detours can hook any function and could be used here to detour the whole function at 40A1A0. We could rewrite that function in C and use detours to jump to that. It looks like a regular `DWORD* __thiscall fun(void *this)` function which should be detourable (unlike some other functions in the game which have been optimized and would be harder to hook).

**Comment by RhythmLunatic** [comment]
Ok.

I don't know how detours works, but all that's probably needed to be passed in is eax and esi register so they can be used as pointers as detailed here (eax contains location of circle pad, esi contains location of where to write data back to for the game) https://github.com/RhythmLunatic/random-scripts/blob/master/Touhou%2012.3%20DPad%20Fix.txt

I think 40DC0 sets up the registers but tbh I don't understand it other than knowing NOPing it will crash the game.

**Comment by delthas** [comment]
Merged in https://github.com/delthas/SWRSToys/commit/eee58947e34a416870df5e437a1d83bb30a792be

I'm too lazy to hook the input function nicely.

Thanks!

**Pull request closed without merging**
